<template>
  <div>
    <c-container>
      <c-header>Header</c-header>
      <c-container>
        <c-aside>Aside</c-aside>
        <c-container>
          <c-main>Main</c-main>
        </c-container>
      </c-container>
      <c-footer>Footer</c-footer>
    </c-container>
  </div>
</template>
